<a href="https://colab.research.google.com/github/xychong/edgeaimonitoring/blob/main/Train_and_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import librosa, librosa.display
import numpy as np
import os
import IPython
import pandas as pd

# make plot outputs appear and be stored within notebook
%matplotlib inline

import sklearn
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pathname_ambience = "/content/drive/MyDrive/FYP Data/Data (2500)/Ambience"
pathname_footsteps = "/content/drive/MyDrive/FYP Data/Data (2500)/Footsteps"
pathname_horn = "/content/drive/MyDrive/FYP Data/Data (2500)/Horn"
pathname_music = "/content/drive/MyDrive/FYP Data/Data (2500)/Music"
pathname_shout = "/content/drive/MyDrive/FYP Data/Data (2500)/Shout"

### Ambience

In [ ]:
df_melspec_ambience = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [ ]:
# Window size = 2048
# Number of Features = sample_rate/hop_length * duration_of_audio
# Compute FFT for each window
# Take entire frequency spectrum and separate into 224 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_ambience):
  audiopath = pathname_ambience + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  duration = librosa.get_duration(y)/2
  hop_len = round(44100/(224/duration))
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = hop_len, n_mels=224, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_ambience = df_melspec_ambience.append({'Class': "Ambience",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 

In [ ]:
df_melspec_ambience.head()

Class  ...                                Log Mel Spectrogram
0  Ambience  ...  [[[-23.015066, -23.015066, -23.015066], [-36.7...
1  Ambience  ...  [[[-35.291317, -35.291317, -35.291317], [-37.1...
2  Ambience  ...  [[[-28.944914, -28.944914, -28.944914], [-33.7...
3  Ambience  ...  [[[-41.734478, -41.734478, -41.734478], [-45.7...
4  Ambience  ...  [[[-40.293793, -40.293793, -40.293793], [-38.5...

[5 rows x 3 columns]

In [ ]:
melspec_list = np.array(df_melspec_ambience['Log Mel Spectrogram'].values.tolist())

In [ ]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 

In [ ]:
df_input = df_melspec_ambience[['Filename','Log Mel Spectrogram']]
train_ambience, test_ambience = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_ambience

Filename                                Log Mel Spectrogram
389  ambience (439).wav  [[[-12.129162, -12.129162, -12.129162], [-19.7...
233   ambience (73).wav  [[[-25.367601, -25.367601, -25.367601], [-43.0...
235   ambience (81).wav  [[[-22.84408, -22.84408, -22.84408], [-35.5518...
309   ambience (15).wav  [[[-43.603523, -43.603523, -43.603523], [-32.6...
262   ambience (50).wav  [[[-26.005686, -26.005686, -26.005686], [-46.7...
..                  ...                                                ...
407  ambience (427).wav  [[[-24.166763, -24.166763, -24.166763], [-20.1...
207  ambience (123).wav  [[[-26.508297, -26.508297, -26.508297], [-28.8...
14   ambience (319).wav  [[[-37.62004, -37.62004, -37.62004], [-32.8695...
38   ambience (297).wav  [[[-32.40503, -32.40503, -32.40503], [-36.1716...
96   ambience (206).wav  [[[-40.700413, -40.700413, -40.700413], [-38.3...

[400 rows x 2 columns]

In [ ]:
test_ambience

Filename                                Log Mel Spectrogram
51   ambience (269).wav  [[[-14.47392, -14.47392, -14.47392], [-33.8815...
338  ambience (493).wav  [[[-18.333828, -18.333828, -18.333828], [-30.2...
378  ambience (474).wav  [[[-16.491426, -16.491426, -16.491426], [-15.7...
321  ambience (329).wav  [[[-14.09032, -14.09032, -14.09032], [-12.8405...
210   ambience (97).wav  [[[-31.390665, -31.390665, -31.390665], [-42.0...
..                  ...                                                ...
114  ambience (197).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
252   ambience (47).wav  [[[-24.532852, -24.532852, -24.532852], [-44.3...
296   ambience (14).wav  [[[-9.511655, -9.511655, -9.511655], [-5.11737...
257   ambience (59).wav  [[[-28.092192, -28.092192, -28.092192], [-44.2...
122  ambience (182).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...

[100 rows x 2 columns]

### Footsteps

In [ ]:
df_melspec_footsteps = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [ ]:
# Window size = 2048
# Number of Features = sample_rate/hop_length * duration_of_audio
# Compute FFT for each window
# Take entire frequency spectrum and separate into 224 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_footsteps):
  audiopath = pathname_footsteps + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  duration = librosa.get_duration(y)/2
  hop_len = round(44100/(224/duration))
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = hop_len, n_mels=224, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_footsteps = df_melspec_footsteps.append({'Class': "Footsteps",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [ ]:
df_melspec_footsteps.head()

Class  ...                                Log Mel Spectrogram
0  Footsteps  ...  [[[-49.480644, -49.480644, -49.480644], [-42.0...
1  Footsteps  ...  [[[-36.579136, -36.579136, -36.579136], [-46.3...
2  Footsteps  ...  [[[-32.801277, -32.801277, -32.801277], [-23.4...
3  Footsteps  ...  [[[-44.793125, -44.793125, -44.793125], [-42.6...
4  Footsteps  ...  [[[-47.264633, -47.264633, -47.264633], [-40.9...

[5 rows x 3 columns]

In [ ]:
melspec_list = np.array(df_melspec_footsteps['Log Mel Spectrogram'].values.tolist())

In [ ]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 

In [ ]:
df_input = df_melspec_footsteps[['Filename','Log Mel Spectrogram']]
train_footsteps, test_footsteps = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_footsteps

Filename                                Log Mel Spectrogram
66   footsteps (261).wav  [[[-32.4122, -32.4122, -32.4122], [-32.344368,...
264  footsteps (159).wav  [[[-52.06018, -52.06018, -52.06018], [-52.5267...
469  footsteps (362).wav  [[[-46.58456, -46.58456, -46.58456], [-50.4209...
497  footsteps (240).wav  [[[-19.949032, -19.949032, -19.949032], [-9.39...
90   footsteps (193).wav  [[[-18.413654, -18.413654, -18.413654], [-20.5...
..                   ...                                                ...
155  footsteps (110).wav  [[[-34.59888, -34.59888, -34.59888], [-29.7167...
190   footsteps (56).wav  [[[-37.784325, -37.784325, -37.784325], [-35.0...
477  footsteps (363).wav  [[[-40.627075, -40.627075, -40.627075], [-57.6...
425  footsteps (406).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
252  footsteps (167).wav  [[[-40.32669, -40.32669, -40.32669], [-58.1240...

[400 rows x 2 columns]

In [ ]:
test_footsteps

Filename                                Log Mel Spectrogram
110  footsteps (178).wav  [[[-32.179806, -32.179806, -32.179806], [-30.2...
373  footsteps (446).wav  [[[-29.87858, -29.87858, -29.87858], [-16.0291...
386  footsteps (468).wav  [[[-38.540253, -38.540253, -38.540253], [-27.4...
3     footsteps (13).wav  [[[-44.793125, -44.793125, -44.793125], [-42.6...
466  footsteps (410).wav  [[[-63.137775, -63.137775, -63.137775], [-67.9...
..                   ...                                                ...
436  footsteps (393).wav  [[[-68.24401, -68.24401, -68.24401], [-80.0, -...
109  footsteps (188).wav  [[[-24.561024, -24.561024, -24.561024], [-21.2...
404  footsteps (457).wav  [[[-63.83846, -63.83846, -63.83846], [-71.8163...
214   footsteps (34).wav  [[[-44.36734, -44.36734, -44.36734], [-45.4792...
73   footsteps (250).wav  [[[-29.351099, -29.351099, -29.351099], [-27.8...

[100 rows x 2 columns]

### Horn

In [ ]:
df_melspec_horn = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [ ]:
# Window size = 2048
# Number of Features = sample_rate/hop_length * duration_of_audio
# Compute FFT for each window
# Take entire frequency spectrum and separate into 224 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_horn):
  audiopath = pathname_horn + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  duration = librosa.get_duration(y)/2
  hop_len = round(44100/(224/duration))
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = hop_len, n_mels=224, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_horn = df_melspec_horn.append({'Class': "Horn",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [ ]:
df_melspec_horn.head()

Class       Filename                                Log Mel Spectrogram
0  Horn  horn (28).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
1  Horn  horn (20).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
2  Horn  horn (39).wav  [[[-64.84104, -64.84104, -64.84104], [-60.9975...
3  Horn  horn (19).wav  [[[-74.74084, -74.74084, -74.74084], [-63.9060...
4  Horn  horn (43).wav  [[[-27.015419, -27.015419, -27.015419], [-28.3...

In [ ]:
melspec_list = np.array(df_melspec_horn['Log Mel Spectrogram'].values.tolist())

In [ ]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 

In [ ]:
df_input = df_melspec_horn[['Filename','Log Mel Spectrogram']]
train_horn, test_horn = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_horn

Filename                                Log Mel Spectrogram
183   horn (85).wav  [[[-19.411922, -19.411922, -19.411922], [-20.1...
256  horn (370).wav  [[[-58.64535, -58.64535, -58.64535], [-54.2356...
287  horn (318).wav  [[[-42.688736, -42.688736, -42.688736], [-25.8...
28   horn (227).wav  [[[-36.99231, -36.99231, -36.99231], [-26.2460...
437  horn (287).wav  [[[-23.309446, -23.309446, -23.309446], [-20.3...
..              ...                                                ...
142   horn (55).wav  [[[-43.734974, -43.734974, -43.734974], [-40.9...
464  horn (275).wav  [[[-48.993298, -48.993298, -48.993298], [-41.7...
252  horn (360).wav  [[[-35.60373, -35.60373, -35.60373], [-22.1560...
170  horn (101).wav  [[[-25.094868, -25.094868, -25.094868], [-16.8...
200  horn (118).wav  [[[-24.987438, -24.987438, -24.987438], [-26.3...

[400 rows x 2 columns]

In [ ]:
test_horn

Filename                                Log Mel Spectrogram
23    horn (16).wav  [[[-14.561246, -14.561246, -14.561246], [-17.6...
405  horn (453).wav  [[[-36.13535, -36.13535, -36.13535], [-35.8486...
47   horn (221).wav  [[[-24.148363, -24.148363, -24.148363], [-23.9...
69   horn (171).wav  [[[-38.264854, -38.264854, -38.264854], [-23.6...
321  horn (322).wav  [[[-44.54071, -44.54071, -44.54071], [-44.4244...
..              ...                                                ...
476  horn (256).wav  [[[-31.864641, -31.864641, -31.864641], [-30.2...
472  horn (274).wav  [[[-45.556026, -45.556026, -45.556026], [-47.9...
267  horn (351).wav  [[[-42.953884, -42.953884, -42.953884], [-37.9...
231  horn (379).wav  [[[-38.34242, -38.34242, -38.34242], [-47.1304...
458  horn (262).wav  [[[-31.477793, -31.477793, -31.477793], [-28.4...

[100 rows x 2 columns]

### Music

In [ ]:
df_melspec_music = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [ ]:
# Window size = 2048
# Number of Features = sample_rate/hop_length * duration_of_audio
# Compute FFT for each window
# Take entire frequency spectrum and separate into 224 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_music):
  audiopath = pathname_music + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  duration = librosa.get_duration(y)/2
  hop_len = round(44100/(224/duration))
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = hop_len, n_mels=224, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_music = df_melspec_music.append({'Class': "Music",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [ ]:
df_melspec_music.head()

Class        Filename                                Log Mel Spectrogram
0  Music  music (15).wav  [[[-33.532093, -33.532093, -33.532093], [-52.8...
1  Music  music (14).wav  [[[-22.662294, -22.662294, -22.662294], [-44.8...
2  Music  music (11).wav  [[[-28.591068, -28.591068, -28.591068], [-47.6...
3  Music  music (12).wav  [[[-28.80003, -28.80003, -28.80003], [-45.9442...
4  Music  music (10).wav  [[[-49.95333, -49.95333, -49.95333], [-58.5572...

In [ ]:
melspec_list = np.array(df_melspec_music['Log Mel Spectrogram'].values.tolist())

In [ ]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 

In [ ]:
df_input = df_melspec_music[['Filename','Log Mel Spectrogram']]
train_music, test_music = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_music

Filename                                Log Mel Spectrogram
381  music (362).wav  [[[-25.988876, -25.988876, -25.988876], [-38.6...
322  music (166).wav  [[[-13.406969, -13.406969, -13.406969], [-37.1...
469  music (486).wav  [[[-37.47528, -37.47528, -37.47528], [-38.5249...
27   music (329).wav  [[[-17.0827, -17.0827, -17.0827], [-22.978819,...
274   music (72).wav  [[[-3.4850187, -3.4850187, -3.4850187], [-11.4...
..               ...                                                ...
270   music (45).wav  [[[-16.798975, -16.798975, -16.798975], [-14.6...
52   music (299).wav  [[[-26.246857, -26.246857, -26.246857], [-25.6...
326  music (143).wav  [[[-36.06378, -36.06378, -36.06378], [-33.6621...
264   music (66).wav  [[[-31.735334, -31.735334, -31.735334], [-27.3...
98   music (195).wav  [[[-56.307083, -56.307083, -56.307083], [-69.0...

[400 rows x 2 columns]

In [ ]:
test_music

Filename                                Log Mel Spectrogram
153  music (253).wav  [[[-31.047441, -31.047441, -31.047441], [-44.4...
278   music (55).wav  [[[-15.608436, -15.608436, -15.608436], [-8.09...
71   music (213).wav  [[[-26.577095, -26.577095, -26.577095], [-24.0...
262   music (44).wav  [[[-46.301983, -46.301983, -46.301983], [-64.9...
79   music (238).wav  [[[-32.411087, -32.411087, -32.411087], [-37.4...
..               ...                                                ...
42   music (315).wav  [[[-27.286615, -27.286615, -27.286615], [-37.2...
364  music (377).wav  [[[-44.795357, -44.795357, -44.795357], [-58.7...
250   music (61).wav  [[[-21.682608, -21.682608, -21.682608], [-6.05...
388  music (368).wav  [[[-47.072365, -47.072365, -47.072365], [-39.9...
187  music (257).wav  [[[-12.571274, -12.571274, -12.571274], [-7.87...

[100 rows x 2 columns]

### Shout

In [ ]:
df_melspec_shout = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [ ]:
# Window size = 2048
# Number of Features = sample_rate/hop_length * duration_of_audio
# Compute FFT for each window
# Take entire frequency spectrum and separate into 224 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_shout):
  audiopath = pathname_shout + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  duration = librosa.get_duration(y)/2
  hop_len = round(44100/(224/duration))
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = hop_len, n_mels=224, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_shout = df_melspec_shout.append({'Class': "Shout",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [ ]:
df_melspec_shout.head()

Class         Filename                                Log Mel Spectrogram
0  Shout  shout (251).wav  [[[-48.21131, -48.21131, -48.21131], [-42.7343...
1  Shout  shout (248).wav  [[[-58.597908, -58.597908, -58.597908], [-45.8...
2  Shout  shout (266).wav  [[[-76.53251, -76.53251, -76.53251], [-80.0, -...
3  Shout  shout (270).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
4  Shout  shout (240).wav  [[[-38.6855, -38.6855, -38.6855], [-38.668934,...

In [ ]:
melspec_list = np.array(df_melspec_shout['Log Mel Spectrogram'].values.tolist())

In [ ]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 224, 3)
(224, 

In [ ]:
df_input = df_melspec_shout[['Filename','Log Mel Spectrogram']]
train_shout, test_shout = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_shout

Filename                                Log Mel Spectrogram
400   shout (96).wav  [[[-39.681534, -39.681534, -39.681534], [-41.7...
403   shout (76).wav  [[[-64.9897, -64.9897, -64.9897], [-56.29178, ...
2    shout (266).wav  [[[-76.53251, -76.53251, -76.53251], [-80.0, -...
147  shout (332).wav  [[[-38.699303, -38.699303, -38.699303], [-54.7...
405   shout (62).wav  [[[-41.656418, -41.656418, -41.656418], [-46.7...
..               ...                                                ...
233  shout (465).wav  [[[-77.59317, -77.59317, -77.59317], [-80.0, -...
104  shout (350).wav  [[[-36.933594, -36.933594, -36.933594], [-52.4...
209  shout (392).wav  [[[-79.36642, -79.36642, -79.36642], [-77.2765...
441   shout (73).wav  [[[-55.39186, -55.39186, -55.39186], [-48.9187...
255    shout (3).wav  [[[-60.57174, -60.57174, -60.57174], [-61.8400...

[400 rows x 2 columns]

In [ ]:
test_shout

Filename                                Log Mel Spectrogram
327  shout (143).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
455  shout (204).wav  [[[-66.98196, -66.98196, -66.98196], [-50.0785...
208  shout (408).wav  [[[-52.71028, -52.71028, -52.71028], [-66.3032...
471   shout (30).wav  [[[-75.16519, -75.16519, -75.16519], [-72.7935...
322  shout (151).wav  [[[-50.112434, -50.112434, -50.112434], [-48.9...
..               ...                                                ...
56   shout (306).wav  [[[-78.87864, -78.87864, -78.87864], [-70.6659...
395   shout (81).wav  [[[-45.5764, -45.5764, -45.5764], [-52.51882, ...
353   shout (36).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
37   shout (311).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
0    shout (251).wav  [[[-48.21131, -48.21131, -48.21131], [-42.7343...

[100 rows x 2 columns]

### Merge all train dataframes into one dataframe

In [ ]:
df_train_append1 = train_ambience.append(train_footsteps)
df_train_append2 = df_train_append1.append(train_horn)
df_train_append3 = df_train_append2.append(train_music)
df_train = df_train_append3.append(train_shout)
df_train

Filename                                Log Mel Spectrogram
389  ambience (439).wav  [[[-12.129162, -12.129162, -12.129162], [-19.7...
233   ambience (73).wav  [[[-25.367601, -25.367601, -25.367601], [-43.0...
235   ambience (81).wav  [[[-22.84408, -22.84408, -22.84408], [-35.5518...
309   ambience (15).wav  [[[-43.603523, -43.603523, -43.603523], [-32.6...
262   ambience (50).wav  [[[-26.005686, -26.005686, -26.005686], [-46.7...
..                  ...                                                ...
233     shout (465).wav  [[[-77.59317, -77.59317, -77.59317], [-80.0, -...
104     shout (350).wav  [[[-36.933594, -36.933594, -36.933594], [-52.4...
209     shout (392).wav  [[[-79.36642, -79.36642, -79.36642], [-77.2765...
441      shout (73).wav  [[[-55.39186, -55.39186, -55.39186], [-48.9187...
255       shout (3).wav  [[[-60.57174, -60.57174, -60.57174], [-61.8400...

[2000 rows x 2 columns]

In [ ]:
df_train_final = df_train.drop(['Filename'], axis = 1)
df_train_final

Log Mel Spectrogram
389  [[[-12.129162, -12.129162, -12.129162], [-19.7...
233  [[[-25.367601, -25.367601, -25.367601], [-43.0...
235  [[[-22.84408, -22.84408, -22.84408], [-35.5518...
309  [[[-43.603523, -43.603523, -43.603523], [-32.6...
262  [[[-26.005686, -26.005686, -26.005686], [-46.7...
..                                                 ...
233  [[[-77.59317, -77.59317, -77.59317], [-80.0, -...
104  [[[-36.933594, -36.933594, -36.933594], [-52.4...
209  [[[-79.36642, -79.36642, -79.36642], [-77.2765...
441  [[[-55.39186, -55.39186, -55.39186], [-48.9187...
255  [[[-60.57174, -60.57174, -60.57174], [-61.8400...

[2000 rows x 1 columns]

### Merge all test dataframes into one dataframe

In [ ]:
df_test_append1 = test_ambience.append(test_footsteps)
df_test_append2 = df_test_append1.append(test_horn)
df_test_append3 = df_test_append2.append(test_music)
df_test = df_test_append3.append(test_shout)
df_test

Filename                                Log Mel Spectrogram
51   ambience (269).wav  [[[-14.47392, -14.47392, -14.47392], [-33.8815...
338  ambience (493).wav  [[[-18.333828, -18.333828, -18.333828], [-30.2...
378  ambience (474).wav  [[[-16.491426, -16.491426, -16.491426], [-15.7...
321  ambience (329).wav  [[[-14.09032, -14.09032, -14.09032], [-12.8405...
210   ambience (97).wav  [[[-31.390665, -31.390665, -31.390665], [-42.0...
..                  ...                                                ...
56      shout (306).wav  [[[-78.87864, -78.87864, -78.87864], [-70.6659...
395      shout (81).wav  [[[-45.5764, -45.5764, -45.5764], [-52.51882, ...
353      shout (36).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
37      shout (311).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
0       shout (251).wav  [[[-48.21131, -48.21131, -48.21131], [-42.7343...

[500 rows x 2 columns]

In [ ]:
df_test_final = df_test.drop(['Filename'], axis = 1)
df_test_final

Log Mel Spectrogram
51   [[[-14.47392, -14.47392, -14.47392], [-33.8815...
338  [[[-18.333828, -18.333828, -18.333828], [-30.2...
378  [[[-16.491426, -16.491426, -16.491426], [-15.7...
321  [[[-14.09032, -14.09032, -14.09032], [-12.8405...
210  [[[-31.390665, -31.390665, -31.390665], [-42.0...
..                                                 ...
56   [[[-78.87864, -78.87864, -78.87864], [-70.6659...
395  [[[-45.5764, -45.5764, -45.5764], [-52.51882, ...
353  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
37   [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
0    [[[-48.21131, -48.21131, -48.21131], [-42.7343...

[500 rows x 1 columns]

### Export train and test data into npy files

In [ ]:
train_data = np.empty(shape=(df_train_final.shape[0], 224, 224, 3))
train_list = np.array(df_train_final['Log Mel Spectrogram'].values.tolist())

print(train_list[2])
print(train_list.shape)

[[[-22.84408  -22.84408  -22.84408 ]
  [-35.55183  -35.55183  -35.55183 ]
  [-40.490917 -40.490917 -40.490917]
  ...
  [-35.019848 -35.019848 -35.019848]
  [-36.382946 -36.382946 -36.382946]
  [-37.040337 -37.040337 -37.040337]]

 [[-22.15467  -22.15467  -22.15467 ]
  [-32.654457 -32.654457 -32.654457]
  [-38.526512 -38.526512 -38.526512]
  ...
  [-38.451984 -38.451984 -38.451984]
  [-36.96097  -36.96097  -36.96097 ]
  [-40.275246 -40.275246 -40.275246]]

 [[-21.367325 -21.367325 -21.367325]
  [-30.75169  -30.75169  -30.75169 ]
  [-39.12229  -39.12229  -39.12229 ]
  ...
  [-37.33256  -37.33256  -37.33256 ]
  [-36.034325 -36.034325 -36.034325]
  [-42.735577 -42.735577 -42.735577]]

 ...

 [[-52.092415 -52.092415 -52.092415]
  [-53.394596 -53.394596 -53.394596]
  [-50.65332  -50.65332  -50.65332 ]
  ...
  [-50.34676  -50.34676  -50.34676 ]
  [-51.021736 -51.021736 -51.021736]
  [-50.124123 -50.124123 -50.124123]]

 [[-49.6565   -49.6565   -49.6565  ]
  [-53.504265 -53.504265 -53.504265]


In [ ]:
train_list = np.array(df_train_final['Log Mel Spectrogram'].values.tolist())
np.save("/content/drive/MyDrive/FYP Data/Train and Test/train_data.npy", train_list)

In [ ]:
train = np.load("/content/drive/MyDrive/FYP Data/Train and Test/train_data.npy", allow_pickle = True)
print(train.shape)

(2000, 224, 224, 3)


In [ ]:
test_data = np.empty(shape=(df_test_final.shape[0], 224, 224, 3))
test_list = np.array(df_test_final['Log Mel Spectrogram'].values.tolist())

print(test_list[2])

[[[-16.491426  -16.491426  -16.491426 ]
  [-15.729523  -15.729523  -15.729523 ]
  [-17.209515  -17.209515  -17.209515 ]
  ...
  [-24.855202  -24.855202  -24.855202 ]
  [-19.53215   -19.53215   -19.53215  ]
  [-12.956652  -12.956652  -12.956652 ]]

 [[-18.41176   -18.41176   -18.41176  ]
  [-17.492884  -17.492884  -17.492884 ]
  [-15.413301  -15.413301  -15.413301 ]
  ...
  [ -9.670636   -9.670636   -9.670636 ]
  [-11.164694  -11.164694  -11.164694 ]
  [-15.3231945 -15.3231945 -15.3231945]]

 [[-17.08043   -17.08043   -17.08043  ]
  [-18.439997  -18.439997  -18.439997 ]
  [-14.972219  -14.972219  -14.972219 ]
  ...
  [ -6.008489   -6.008489   -6.008489 ]
  [ -8.619207   -8.619207   -8.619207 ]
  [-12.057499  -12.057499  -12.057499 ]]

 ...

 [[-66.27282   -66.27282   -66.27282  ]
  [-75.41408   -75.41408   -75.41408  ]
  [-75.31243   -75.31243   -75.31243  ]
  ...
  [-75.05936   -75.05936   -75.05936  ]
  [-76.877174  -76.877174  -76.877174 ]
  [-77.03882   -77.03882   -77.03882  ]]

 [

In [ ]:
test_list = np.array(df_test_final['Log Mel Spectrogram'].values.tolist())
np.save("/content/drive/MyDrive/FYP Data/Train and Test/test_data.npy", test_list)

In [ ]:
test = np.load("/content/drive/MyDrive/FYP Data/Train and Test/test_data.npy", allow_pickle = True)
print(test.shape)

(500, 224, 224, 3)


### Obtain train and test labels

In [ ]:
df_train

Filename                                Log Mel Spectrogram
389  ambience (439).wav  [[[-12.129162, -12.129162, -12.129162], [-19.7...
233   ambience (73).wav  [[[-25.367601, -25.367601, -25.367601], [-43.0...
235   ambience (81).wav  [[[-22.84408, -22.84408, -22.84408], [-35.5518...
309   ambience (15).wav  [[[-43.603523, -43.603523, -43.603523], [-32.6...
262   ambience (50).wav  [[[-26.005686, -26.005686, -26.005686], [-46.7...
..                  ...                                                ...
233     shout (465).wav  [[[-77.59317, -77.59317, -77.59317], [-80.0, -...
104     shout (350).wav  [[[-36.933594, -36.933594, -36.933594], [-52.4...
209     shout (392).wav  [[[-79.36642, -79.36642, -79.36642], [-77.2765...
441      shout (73).wav  [[[-55.39186, -55.39186, -55.39186], [-48.9187...
255       shout (3).wav  [[[-60.57174, -60.57174, -60.57174], [-61.8400...

[2000 rows x 2 columns]

In [ ]:
# Creating an empty list
train_label = []

In [ ]:
# Creating an empty list
train_label = []

for item in df_train['Filename']:
  filename = str(item)
  sound_class = filename.split()[0] # Only obtain first word
  if sound_class == "ambience":
    train_label.append(0)
  if sound_class == "footsteps":
    train_label.append(1)
  if sound_class == "horn":
    train_label.append(2)
  if sound_class == "music":
    train_label.append(3)
  if sound_class == "shout":
    train_label.append(4)

train_label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [ ]:
df_test

Filename                                Log Mel Spectrogram
51   ambience (269).wav  [[[-14.47392, -14.47392, -14.47392], [-33.8815...
338  ambience (493).wav  [[[-18.333828, -18.333828, -18.333828], [-30.2...
378  ambience (474).wav  [[[-16.491426, -16.491426, -16.491426], [-15.7...
321  ambience (329).wav  [[[-14.09032, -14.09032, -14.09032], [-12.8405...
210   ambience (97).wav  [[[-31.390665, -31.390665, -31.390665], [-42.0...
..                  ...                                                ...
56      shout (306).wav  [[[-78.87864, -78.87864, -78.87864], [-70.6659...
395      shout (81).wav  [[[-45.5764, -45.5764, -45.5764], [-52.51882, ...
353      shout (36).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
37      shout (311).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
0       shout (251).wav  [[[-48.21131, -48.21131, -48.21131], [-42.7343...

[500 rows x 2 columns]

In [ ]:
# Creating an empty list
test_label = []

for item in df_test['Filename']:
  filename = str(item)
  sound_class = filename.split()[0] # Only obtain first word
  if sound_class == "ambience":
    test_label.append(0)
  if sound_class == "footsteps":
    test_label.append(1)
  if sound_class == "horn":
    test_label.append(2)
  if sound_class == "music":
    test_label.append(3)
  if sound_class == "shout":
    test_label.append(4)

test_label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,


In [ ]:
train_label_newdim = np.expand_dims(train_label, axis=1)
test_label_newdim = np.expand_dims(test_label, axis=1)

print(train_label_newdim)

[[0]
 [0]
 [0]
 ...
 [4]
 [4]
 [4]]


In [ ]:
train_label_newdim = np.expand_dims(train_label, axis=1)
test_label_newdim = np.expand_dims(test_label, axis=1)
np.save("/content/drive/MyDrive/FYP Data/Train and Test/train_label.npy", train_label_newdim)
np.save("/content/drive/MyDrive/FYP Data/Train and Test/test_label.npy", test_label_newdim)

In [ ]:
train_labels = np.load("/content/drive/MyDrive/FYP Data/Train and Test/train_label.npy", allow_pickle = True)
test_labels = np.load("/content/drive/MyDrive/FYP Data/Train and Test/test_label.npy", allow_pickle = True)

print(train_labels.shape)
print(test_labels.shape)

(2000, 1)
(500, 1)
