<a href="https://colab.research.google.com/github/xychong/edgeaimonitoring/blob/main/Train_and_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import librosa, librosa.display
import numpy as np
import os
import IPython
import pandas as pd

# make plot outputs appear and be stored within notebook
%matplotlib inline

import sklearn
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
pathname_ambience = "/content/drive/MyDrive/FYP Data/Data/Ambience/"
pathname_footsteps = "/content/drive/MyDrive/FYP Data/Data/Footsteps/"
pathname_horn = "/content/drive/MyDrive/FYP Data/Data/Horn/"
pathname_music = "/content/drive/MyDrive/FYP Data/Data/Music/"
pathname_shout = "/content/drive/MyDrive/FYP Data/Data/Shout/"

### Ambience

In [4]:
df_melspec_ambience = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [5]:
# Window size = 2048
# Hop size = 512
# Compute FFT for each window
# Take entire frequency spectrum and separate into 345 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_ambience):
  audiopath = pathname_ambience + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = 512, n_mels=345, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_ambience = df_melspec_ambience.append({'Class': "Ambience",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [7]:
df_melspec_ambience.head()

Class  ...                                Log Mel Spectrogram
0  Ambience  ...  [[[-64.589325, -64.589325, -64.589325], [-44.5...
1  Ambience  ...  [[[-46.359592, -46.359592, -46.359592], [-47.0...
2  Ambience  ...  [[[-40.281746, -40.281746, -40.281746], [-47.0...
3  Ambience  ...  [[[-40.819183, -40.819183, -40.819183], [-45.8...
4  Ambience  ...  [[[-47.165558, -47.165558, -47.165558], [-53.2...

[5 rows x 3 columns]

In [8]:
melspec_list = np.array(df_melspec_ambience['Log Mel Spectrogram'].values.tolist())

In [9]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 

In [12]:
df_input = df_melspec_ambience[['Filename','Log Mel Spectrogram']]
train_ambience, test_ambience = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_ambience

Filename                                Log Mel Spectrogram
270  ambience (110).wav  [[[-33.08299, -33.08299, -33.08299], [-38.4111...
102  ambience (206).wav  [[[-35.107437, -35.107437, -35.107437], [-40.7...
197  ambience (130).wav  [[[-23.944202, -23.944202, -23.944202], [-24.7...
142  ambience (182).wav  [[[-39.812046, -39.812046, -39.812046], [-44.6...
53   ambience (271).wav  [[[-28.620619, -28.620619, -28.620619], [-28.3...
..                  ...                                                ...
271   ambience (47).wav  [[[-32.387253, -32.387253, -32.387253], [-37.8...
293    ambience (6).wav  [[[-40.24123, -40.24123, -40.24123], [-41.8383...
112  ambience (203).wav  [[[-66.08594, -66.08594, -66.08594], [-54.8495...
116  ambience (184).wav  [[[-56.168037, -56.168037, -56.168037], [-67.2...
44   ambience (257).wav  [[[-37.66739, -37.66739, -37.66739], [-43.2672...

[256 rows x 2 columns]

In [13]:
test_ambience

Filename                                Log Mel Spectrogram
167  ambience (132).wav  [[[-44.501633, -44.501633, -44.501633], [-31.9...
318  ambience (321).wav  [[[-20.341702, -20.341702, -20.341702], [-23.5...
72   ambience (252).wav  [[[-24.07206, -24.07206, -24.07206], [-23.9069...
3    ambience (300).wav  [[[-40.819183, -40.819183, -40.819183], [-45.8...
185  ambience (192).wav  [[[-40.354637, -40.354637, -40.354637], [-45.9...
..                  ...                                                ...
314   ambience (12).wav  [[[-45.51901, -45.51901, -45.51901], [-47.4332...
42   ambience (261).wav  [[[-27.42527, -27.42527, -27.42527], [-31.3088...
126  ambience (209).wav  [[[-64.01073, -64.01073, -64.01073], [-64.0619...
316    ambience (1).wav  [[[-28.40573, -28.40573, -28.40573], [-29.3921...
38   ambience (289).wav  [[[-41.3422, -41.3422, -41.3422], [-45.141335,...

[65 rows x 2 columns]

### Footsteps

In [17]:
df_melspec_footsteps = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [18]:
# Window size = 2048
# Hop size = 512
# Compute FFT for each window
# Take entire frequency spectrum and separate into 345 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_footsteps):
  audiopath = pathname_footsteps + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = 512, n_mels=345, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_footsteps = df_melspec_footsteps.append({'Class': "Footsteps",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [19]:
df_melspec_footsteps.head()

Class  ...                                Log Mel Spectrogram
0  Footsteps  ...  [[[-46.995945, -46.995945, -46.995945], [-48.3...
1  Footsteps  ...  [[[-29.431768, -29.431768, -29.431768], [-29.1...
2  Footsteps  ...  [[[-50.14822, -50.14822, -50.14822], [-53.7723...
3  Footsteps  ...  [[[-43.041107, -43.041107, -43.041107], [-32.6...
4  Footsteps  ...  [[[-47.934456, -47.934456, -47.934456], [-28.1...

[5 rows x 3 columns]

In [20]:
melspec_list = np.array(df_melspec_footsteps['Log Mel Spectrogram'].values.tolist())

In [21]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 

In [25]:
df_input = df_melspec_footsteps[['Filename','Log Mel Spectrogram']]
train_footsteps, test_footsteps = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_footsteps

Filename                                Log Mel Spectrogram
19     footsteps (6).wav  [[[-72.777664, -72.777664, -72.777664], [-71.9...
187   footsteps (66).wav  [[[-22.008776, -22.008776, -22.008776], [-25.0...
153  footsteps (109).wav  [[[-27.706394, -27.706394, -27.706394], [-25.5...
53   footsteps (291).wav  [[[-24.56182, -24.56182, -24.56182], [-25.7173...
69   footsteps (251).wav  [[[-74.04463, -74.04463, -74.04463], [-64.9349...
..                   ...                                                ...
90   footsteps (199).wav  [[[-40.74266, -40.74266, -40.74266], [-48.1722...
252  footsteps (142).wav  [[[-70.783226, -70.783226, -70.783226], [-80.0...
66   footsteps (279).wav  [[[-26.684332, -26.684332, -26.684332], [-29.0...
4    footsteps (342).wav  [[[-47.934456, -47.934456, -47.934456], [-28.1...
149  footsteps (116).wav  [[[-30.392033, -30.392033, -30.392033], [-35.3...

[274 rows x 2 columns]

In [26]:
test_footsteps

Filename                                Log Mel Spectrogram
10     footsteps (1).wav  [[[-23.64164, -23.64164, -23.64164], [-26.3956...
238   footsteps (59).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
222   footsteps (26).wav  [[[-60.3381, -60.3381, -60.3381], [-57.767883,...
251  footsteps (160).wav  [[[-80.0, -80.0, -80.0], [-73.524345, -73.5243...
116  footsteps (174).wav  [[[-24.704842, -24.704842, -24.704842], [-23.5...
..                   ...                                                ...
141  footsteps (103).wav  [[[-26.680237, -26.680237, -26.680237], [-31.0...
235   footsteps (48).wav  [[[-47.727676, -47.727676, -47.727676], [-39.7...
321  footsteps (261).wav  [[[-63.349228, -63.349228, -63.349228], [-69.1...
317  footsteps (218).wav  [[[-40.570045, -40.570045, -40.570045], [-39.7...
218   footsteps (11).wav  [[[-5.1043596, -5.1043596, -5.1043596], [-8.63...

[69 rows x 2 columns]

### Horn

In [27]:
df_melspec_horn = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [28]:
# Window size = 2048
# Hop size = 512
# Compute FFT for each window
# Take entire frequency spectrum and separate into 345 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_horn):
  audiopath = pathname_horn + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = 512, n_mels=345, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_horn = df_melspec_horn.append({'Class': "Horn",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [29]:
df_melspec_horn.head()

Class       Filename                                Log Mel Spectrogram
0  Horn  horn (31).wav  [[[-80.0, -80.0, -80.0], [-71.910706, -71.9107...
1  Horn  horn (12).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
2  Horn  horn (20).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
3  Horn  horn (32).wav  [[[-47.88686, -47.88686, -47.88686], [-55.0599...
4  Horn  horn (16).wav  [[[-36.90676, -36.90676, -36.90676], [-42.9522...

In [30]:
melspec_list = np.array(df_melspec_horn['Log Mel Spectrogram'].values.tolist())

In [31]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 

In [32]:
df_input = df_melspec_horn[['Filename','Log Mel Spectrogram']]
train_horn, test_horn = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_horn

Filename                                Log Mel Spectrogram
64   horn (198).wav  [[[-36.339638, -36.339638, -36.339638], [-31.6...
34     horn (3).wav  [[[-22.522083, -22.522083, -22.522083], [-26.3...
203   horn (96).wav  [[[-33.647114, -33.647114, -33.647114], [-38.1...
25   horn (228).wav  [[[-32.11183, -32.11183, -32.11183], [-47.4142...
116  horn (129).wav  [[[-56.435143, -56.435143, -56.435143], [-39.2...
..              ...                                                ...
190   horn (94).wav  [[[-23.553993, -23.553993, -23.553993], [-23.9...
9     horn (11).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
228  horn (116).wav  [[[-42.276814, -42.276814, -42.276814], [-48.2...
171   horn (58).wav  [[[-29.179647, -29.179647, -29.179647], [-30.5...
170   horn (73).wav  [[[-21.35193, -21.35193, -21.35193], [-24.2222...

[185 rows x 2 columns]

In [33]:
test_horn

Filename                                Log Mel Spectrogram
174   horn (71).wav  [[[-25.807938, -25.807938, -25.807938], [-35.4...
88   horn (182).wav  [[[-27.721958, -27.721958, -27.721958], [-35.0...
58   horn (194).wav  [[[-80.0, -80.0, -80.0], [-63.445045, -63.4450...
165   horn (50).wav  [[[-35.07379, -35.07379, -35.07379], [-26.1561...
128  horn (138).wav  [[[-28.90509, -28.90509, -28.90509], [-43.3943...
182   horn (86).wav  [[[-30.66608, -30.66608, -30.66608], [-31.8001...
145   horn (49).wav  [[[-37.700405, -37.700405, -37.700405], [-44.6...
80   horn (162).wav  [[[-29.292944, -29.292944, -29.292944], [-28.9...
84   horn (164).wav  [[[-67.983154, -67.983154, -67.983154], [-30.4...
35   horn (219).wav  [[[-35.43015, -35.43015, -35.43015], [-41.2921...
197  horn (104).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
137  horn (124).wav  [[[-65.01795, -65.01795, -65.01795], [-34.8150...
87   horn (181).wav  [[[-60.979546, -60.979546, -60.979546], [-49.1...
0     horn (31).wav  [[[-80.0, -80.0, -80.0], [-71.910706, -71.9107...
95   horn (179).wav  [[[-37.380577, -37.380577, -37.380577], [-42.0...
167   horn (57).wav  [[[-23.734648, -23.734648, -23.734648], [-29.7...
212  horn (110).wav  [[[-39.371773, -39.371773, -39.371773], [-54.2...
223   horn (27).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
213  horn (108).wav  [[[-12.496772, -12.496772, -12.496772], [-16.8...
75   horn (184).wav  [[[-77.31084, -77.31084, -77.31084], [-52.1262...
195   horn (89).wav  [[[-45.185555, -45.185555, -45.185555], [-55.9...
69   horn (196).wav  [[[-22.319162, -22.319162, -22.319162], [-26.9...
78   horn (186).wav  [[[-27.690897, -27.690897, -27.690897], [-30.7...
39   horn (223).wav  [[[-33.348545, -33.348545, -33.348545], [-31.2...
169   horn (59).wav  [[[-27.267971, -27.267971, -27.267971], [-26.3...
215   horn (25).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
211  horn (113).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
125  horn (139).wav  [[[-36.977886, -36.977886, -36.977886], [-37.9...
164   horn (68).wav  [[[-27.338589, -27.338589, -27.338589], [-36.8...
110  horn (158).wav  [[[-28.572754, -28.572754, -28.572754], [-27.8...
231  horn (122).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
168   horn (60).wav  [[[-23.961266, -23.961266, -23.961266], [-29.6...
217   horn (99).wav  [[[-27.980003, -27.980003, -27.980003], [-30.3...
162   horn (61).wav  [[[-27.489706, -27.489706, -27.489706], [-26.9...
198   horn (95).wav  [[[-29.270216, -29.270216, -29.270216], [-34.1...
89   horn (168).wav  [[[-41.40444, -41.40444, -41.40444], [-29.9172...
108  horn (155).wav  [[[-80.0, -80.0, -80.0], [-34.370407, -34.3704...
188   horn (79).wav  [[[-25.015335, -25.015335, -25.015335], [-29.6...
11    horn (35).wav  [[[-58.701668, -58.701668, -58.701668], [-30.2...
154   horn (62).wav  [[[-30.10394, -30.10394, -30.10394], [-29.2979...
189   horn (63).wav  [[[-20.866074, -20.866074, -20.866074], [-25.2...
97   horn (180).wav  [[[-32.416016, -32.416016, -32.416016], [-42.3...
13    horn (37).wav  [[[-28.46127, -28.46127, -28.46127], [-23.9700...
153   horn (38).wav  [[[-60.786034, -60.786034, -60.786034], [-44.7...
82   horn (163).wav  [[[-22.91866, -22.91866, -22.91866], [-22.3928...
106  horn (154).wav  [[[-35.698967, -35.698967, -35.698967], [-39.0...
70   horn (193).wav  [[[-25.742304, -25.742304, -25.742304], [-30.0...

### Music

In [35]:
df_melspec_music = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [36]:
# Window size = 2048
# Hop size = 512
# Compute FFT for each window
# Take entire frequency spectrum and separate into 345 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_music):
  audiopath = pathname_music + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = 512, n_mels=345, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_music = df_melspec_music.append({'Class': "Music",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [37]:
df_melspec_music.head()

Class       Filename                                Log Mel Spectrogram
0  Music  music (8).wav  [[[-41.944553, -41.944553, -41.944553], [-47.5...
1  Music  music (5).wav  [[[-37.44742, -37.44742, -37.44742], [-43.7889...
2  Music  music (4).wav  [[[-35.821857, -35.821857, -35.821857], [-41.9...
3  Music  music (3).wav  [[[-54.86283, -54.86283, -54.86283], [-60.7735...
4  Music  music (7).wav  [[[-30.553259, -30.553259, -30.553259], [-36.2...

In [38]:
melspec_list = np.array(df_melspec_music['Log Mel Spectrogram'].values.tolist())

In [39]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 

In [40]:
df_input = df_melspec_music[['Filename','Log Mel Spectrogram']]
train_music, test_music = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_music

Filename                                Log Mel Spectrogram
198   music (88).wav  [[[-49.229744, -49.229744, -49.229744], [-50.4...
51   music (293).wav  [[[-33.380367, -33.380367, -33.380367], [-39.3...
206   music (90).wav  [[[-59.356606, -59.356606, -59.356606], [-67.9...
14     music (1).wav  [[[-37.873493, -37.873493, -37.873493], [-44.3...
34   music (318).wav  [[[-36.54314, -36.54314, -36.54314], [-30.5995...
..               ...                                                ...
208   music (95).wav  [[[-38.572178, -38.572178, -38.572178], [-45.3...
8    music (331).wav  [[[-67.74857, -67.74857, -67.74857], [-76.6087...
166  music (257).wav  [[[-44.10531, -44.10531, -44.10531], [-44.2232...
135  music (187).wav  [[[-52.116886, -52.116886, -52.116886], [-58.1...
231   music (77).wav  [[[-41.307575, -41.307575, -41.307575], [-33.9...

[274 rows x 2 columns]

In [41]:
test_music

Filename                                Log Mel Spectrogram
220   music (78).wav  [[[-33.710365, -33.710365, -33.710365], [-35.4...
215  music (105).wav  [[[-51.340065, -51.340065, -51.340065], [-55.7...
109  music (188).wav  [[[-63.143223, -63.143223, -63.143223], [-68.8...
145  music (246).wav  [[[-34.592556, -34.592556, -34.592556], [-39.9...
78   music (235).wav  [[[-46.250435, -46.250435, -46.250435], [-42.3...
..               ...                                                ...
144  music (273).wav  [[[-34.72179, -34.72179, -34.72179], [-40.2422...
272   music (64).wav  [[[-32.79044, -32.79044, -32.79044], [-38.1264...
89   music (202).wav  [[[-41.263023, -41.263023, -41.263023], [-53.7...
294  music (118).wav  [[[-25.499447, -25.499447, -25.499447], [-30.8...
12   music (341).wav  [[[-47.82871, -47.82871, -47.82871], [-53.8035...

[69 rows x 2 columns]

### Shout

In [42]:
df_melspec_shout = pd.DataFrame(columns = ['Class', 'Filename', 'Log Mel Spectrogram'])

In [43]:
# Window size = 2048
# Hop size = 512
# Compute FFT for each window
# Take entire frequency spectrum and separate into 345 evenly spaced frequencies (spaced based on distance heard by human ear)
# For each window, decompose magnitude of signal into its components, corresponding to the frequencies in melscale
for filename in os.listdir(pathname_shout):
  audiopath = pathname_shout + "/" + filename
  y, sr = librosa.load(audiopath, 44100)
  # Minimum Frequency 20 Hz, Maximum Frequency by default 44100/2
  mel_spect = librosa.feature.melspectrogram(y=y, sr=sr, n_fft = 2048, hop_length = 512, n_mels=345, fmin=20)
  log_mel_spect = librosa.power_to_db(mel_spect, ref=np.max)
  log_mel_spect_newdim = np.repeat(log_mel_spect[:,:, np.newaxis], 3, axis =2)
  df_melspec_shout = df_melspec_shout.append({'Class': "Shout",'Filename': filename,'Log Mel Spectrogram': log_mel_spect_newdim}, ignore_index=True)

In [45]:
df_melspec_shout.head()

Class        Filename                                Log Mel Spectrogram
0  Shout  shout (14).wav  [[[-59.581978, -59.581978, -59.581978], [-57.0...
1  Shout  shout (17).wav  [[[-59.914005, -59.914005, -59.914005], [-55.3...
2  Shout  shout (21).wav  [[[-80.0, -80.0, -80.0], [-68.91399, -68.91399...
3  Shout  shout (13).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
4  Shout   shout (8).wav  [[[-73.3937, -73.3937, -73.3937], [-76.30673, ...

In [46]:
melspec_list = np.array(df_melspec_shout['Log Mel Spectrogram'].values.tolist())

In [47]:
# MobileNetv2 Input Shape
# (number of mel bins, number of features, number of channels)
count = 0
for item in melspec_list:
  count += 1
  print(item.shape)

(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 345, 3)
(345, 

In [48]:
df_input = df_melspec_shout[['Filename','Log Mel Spectrogram']]
train_shout, test_shout = train_test_split(df_input, test_size = 0.2, shuffle = True)
train_shout

Filename                                Log Mel Spectrogram
148  shout (233).wav  [[[-51.91977, -51.91977, -51.91977], [-57.9230...
7     shout (27).wav  [[[-75.17001, -75.17001, -75.17001], [-63.9785...
94    shout (85).wav  [[[-71.85879, -71.85879, -71.85879], [-66.5122...
88   shout (100).wav  [[[-76.02086, -76.02086, -76.02086], [-80.0, -...
196  shout (169).wav  [[[-72.453926, -72.453926, -72.453926], [-77.4...
..               ...                                                ...
112  shout (200).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
208  shout (150).wav  [[[-66.7005, -66.7005, -66.7005], [-68.86181, ...
164  shout (133).wav  [[[-70.92355, -70.92355, -70.92355], [-65.4657...
40    shout (53).wav  [[[-58.36692, -58.36692, -58.36692], [-58.7806...
84   shout (105).wav  [[[-74.00872, -74.00872, -74.00872], [-73.0564...

[215 rows x 2 columns]

In [49]:
test_shout

Filename                                Log Mel Spectrogram
134  shout (217).wav  [[[-41.131283, -41.131283, -41.131283], [-46.8...
228  shout (192).wav  [[[-67.086655, -67.086655, -67.086655], [-71.0...
237  shout (246).wav  [[[-44.353935, -44.353935, -44.353935], [-53.4...
83    shout (99).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
121  shout (178).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
74    shout (78).wav  [[[-60.66146, -60.66146, -60.66146], [-52.6190...
10    shout (12).wav  [[[-49.288193, -49.288193, -49.288193], [-46.3...
6     shout (22).wav  [[[-67.130325, -67.130325, -67.130325], [-69.7...
33    shout (62).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
201  shout (164).wav  [[[-78.67434, -78.67434, -78.67434], [-74.4371...
240  shout (186).wav  [[[-64.58293, -64.58293, -64.58293], [-69.7037...
37    shout (57).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
168  shout (120).wav  [[[-68.44121, -68.44121, -68.44121], [-54.8174...
238  shout (231).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
205  shout (183).wav  [[[-78.03673, -78.03673, -78.03673], [-76.4448...
209  shout (149).wav  [[[-80.0, -80.0, -80.0], [-65.81366, -65.81366...
231  shout (229).wav  [[[-72.93748, -72.93748, -72.93748], [-61.5564...
243  shout (247).wav  [[[-51.579124, -51.579124, -51.579124], [-54.1...
71    shout (70).wav  [[[-71.50048, -71.50048, -71.50048], [-74.8529...
165  shout (118).wav  [[[-71.229034, -71.229034, -71.229034], [-76.1...
170  shout (115).wav  [[[-67.086655, -67.086655, -67.086655], [-71.0...
133  shout (179).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
259  shout (224).wav  [[[-59.835487, -59.835487, -59.835487], [-61.9...
131  shout (210).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
160  shout (234).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
195  shout (173).wav  [[[-80.0, -80.0, -80.0], [-73.39308, -73.39308...
85    shout (96).wav  [[[-58.53262, -58.53262, -58.53262], [-62.8669...
9     shout (33).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
44    shout (37).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
45    shout (23).wav  [[[-64.69995, -64.69995, -64.69995], [-72.3994...
140  shout (172).wav  [[[-51.474472, -51.474472, -51.474472], [-49.7...
15    shout (32).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
113  shout (159).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
155  shout (241).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
65    shout (84).wav  [[[-80.0, -80.0, -80.0], [-78.7161, -78.7161, ...
29    shout (51).wav  [[[-80.0, -80.0, -80.0], [-71.83093, -71.83093...
246  shout (184).wav  [[[-47.0213, -47.0213, -47.0213], [-52.283524,...
35    shout (26).wav  [[[-77.20636, -77.20636, -77.20636], [-70.7384...
225  shout (196).wav  [[[-63.462906, -63.462906, -63.462906], [-67.3...
142  shout (236).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
236  shout (248).wav  [[[-50.104073, -50.104073, -50.104073], [-57.2...
163  shout (211).wav  [[[-30.991661, -30.991661, -30.991661], [-37.0...
1     shout (17).wav  [[[-59.914005, -59.914005, -59.914005], [-55.3...
17    shout (34).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
39    shout (42).wav  [[[-80.0, -80.0, -80.0], [-68.03975, -68.03975...
180  shout (135).wav  [[[-57.236626, -57.236626, -57.236626], [-54.7...
182  shout (124).wav  [[[-67.542206, -67.542206, -67.542206], [-73.7...
214  shout (239).wav  [[[-80.0, -80.0, -80.0], [-76.303406, -76.3034...
268    shout (1).wav  [[[-69.18225, -69.18225, -69.18225], [-71.6432...
202  shout (161).wav  [[[-53.830147, -53.830147, -53.830147], [-57.7...
256  shout (266).wav  [[[-80.0, -80.0, -80.0], [-76.28508, -76.28508...
59    shout (74).wav  [[[-80.0, -80.0, -80.0], [-71.82796, -71.82796...
75   shout (112).wav  [[[-80.0, -80.0, -80.0], [-77.284454, -77.2844...
152  shout (243).wav  [[[-80.0, -80.0, -80.0], [-64.71125, -64.71125...

### Merge all train dataframes into one dataframe

In [60]:
df_train_append1 = train_ambience.append(train_footsteps)
df_train_append2 = df_train_append1.append(train_horn)
df_train_append3 = df_train_append2.append(train_music)
df_train = df_train_append3.append(train_shout)
df_train

Filename                                Log Mel Spectrogram
270  ambience (110).wav  [[[-33.08299, -33.08299, -33.08299], [-38.4111...
102  ambience (206).wav  [[[-35.107437, -35.107437, -35.107437], [-40.7...
197  ambience (130).wav  [[[-23.944202, -23.944202, -23.944202], [-24.7...
142  ambience (182).wav  [[[-39.812046, -39.812046, -39.812046], [-44.6...
53   ambience (271).wav  [[[-28.620619, -28.620619, -28.620619], [-28.3...
..                  ...                                                ...
112     shout (200).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
208     shout (150).wav  [[[-66.7005, -66.7005, -66.7005], [-68.86181, ...
164     shout (133).wav  [[[-70.92355, -70.92355, -70.92355], [-65.4657...
40       shout (53).wav  [[[-58.36692, -58.36692, -58.36692], [-58.7806...
84      shout (105).wav  [[[-74.00872, -74.00872, -74.00872], [-73.0564...

[1204 rows x 2 columns]

In [61]:
df_train_final = df_train.drop(['Filename'], axis = 1)
df_train_final

Log Mel Spectrogram
270  [[[-33.08299, -33.08299, -33.08299], [-38.4111...
102  [[[-35.107437, -35.107437, -35.107437], [-40.7...
197  [[[-23.944202, -23.944202, -23.944202], [-24.7...
142  [[[-39.812046, -39.812046, -39.812046], [-44.6...
53   [[[-28.620619, -28.620619, -28.620619], [-28.3...
..                                                 ...
112  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
208  [[[-66.7005, -66.7005, -66.7005], [-68.86181, ...
164  [[[-70.92355, -70.92355, -70.92355], [-65.4657...
40   [[[-58.36692, -58.36692, -58.36692], [-58.7806...
84   [[[-74.00872, -74.00872, -74.00872], [-73.0564...

[1204 rows x 1 columns]

### Merge all test dataframes into one dataframe

In [62]:
df_test_append1 = test_ambience.append(test_footsteps)
df_test_append2 = df_test_append1.append(test_horn)
df_test_append3 = df_test_append2.append(test_music)
df_test = df_test_append3.append(test_shout)
df_test

Filename                                Log Mel Spectrogram
167  ambience (132).wav  [[[-44.501633, -44.501633, -44.501633], [-31.9...
318  ambience (321).wav  [[[-20.341702, -20.341702, -20.341702], [-23.5...
72   ambience (252).wav  [[[-24.07206, -24.07206, -24.07206], [-23.9069...
3    ambience (300).wav  [[[-40.819183, -40.819183, -40.819183], [-45.8...
185  ambience (192).wav  [[[-40.354637, -40.354637, -40.354637], [-45.9...
..                  ...                                                ...
202     shout (161).wav  [[[-53.830147, -53.830147, -53.830147], [-57.7...
256     shout (266).wav  [[[-80.0, -80.0, -80.0], [-76.28508, -76.28508...
59       shout (74).wav  [[[-80.0, -80.0, -80.0], [-71.82796, -71.82796...
75      shout (112).wav  [[[-80.0, -80.0, -80.0], [-77.284454, -77.2844...
152     shout (243).wav  [[[-80.0, -80.0, -80.0], [-64.71125, -64.71125...

[304 rows x 2 columns]

In [63]:
df_test_final = df_test.drop(['Filename'], axis = 1)
df_test_final

Log Mel Spectrogram
167  [[[-44.501633, -44.501633, -44.501633], [-31.9...
318  [[[-20.341702, -20.341702, -20.341702], [-23.5...
72   [[[-24.07206, -24.07206, -24.07206], [-23.9069...
3    [[[-40.819183, -40.819183, -40.819183], [-45.8...
185  [[[-40.354637, -40.354637, -40.354637], [-45.9...
..                                                 ...
202  [[[-53.830147, -53.830147, -53.830147], [-57.7...
256  [[[-80.0, -80.0, -80.0], [-76.28508, -76.28508...
59   [[[-80.0, -80.0, -80.0], [-71.82796, -71.82796...
75   [[[-80.0, -80.0, -80.0], [-77.284454, -77.2844...
152  [[[-80.0, -80.0, -80.0], [-64.71125, -64.71125...

[304 rows x 1 columns]

### Export train and test data into npy files

In [73]:
train_data = np.empty(shape=(df_train_final.shape[0], 345, 345, 3))
train_list = np.array(df_train_final['Log Mel Spectrogram'].values.tolist())

print(train_list[2])

[[[-23.944202 -23.944202 -23.944202]
  [-24.715822 -24.715822 -24.715822]
  [-24.05683  -24.05683  -24.05683 ]
  ...
  [-21.062237 -21.062237 -21.062237]
  [-17.963087 -17.963087 -17.963087]
  [-14.818022 -14.818022 -14.818022]]

 [[-42.823982 -42.823982 -42.823982]
  [-31.546438 -31.546438 -31.546438]
  [-26.66728  -26.66728  -26.66728 ]
  ...
  [-46.49268  -46.49268  -46.49268 ]
  [-21.083515 -21.083515 -21.083515]
  [-18.341131 -18.341131 -18.341131]]

 [[-40.448177 -40.448177 -40.448177]
  [-32.0863   -32.0863   -32.0863  ]
  [-27.585508 -27.585508 -27.585508]
  ...
  [-25.724245 -25.724245 -25.724245]
  [-30.849173 -30.849173 -30.849173]
  [-28.875586 -28.875586 -28.875586]]

 ...

 [[-73.899284 -73.899284 -73.899284]
  [-79.15841  -79.15841  -79.15841 ]
  [-80.       -80.       -80.      ]
  ...
  [-80.       -80.       -80.      ]
  [-80.       -80.       -80.      ]
  [-80.       -80.       -80.      ]]

 [[-73.48602  -73.48602  -73.48602 ]
  [-78.830185 -78.830185 -78.830185]


In [74]:
np.save("/content/drive/MyDrive/FYP Data/Train and Test/train_data.npy", train_list)

In [75]:
train = np.load("/content/drive/MyDrive/FYP Data/Train and Test/train_data.npy", allow_pickle = True)
print(train.shape)

(1204, 345, 345, 3)


In [76]:
test_data = np.empty(shape=(df_test_final.shape[0], 345, 345, 3))
test_list = np.array(df_test_final['Log Mel Spectrogram'].values.tolist())

print(test_list[2])

[[[-24.07206  -24.07206  -24.07206 ]
  [-23.906939 -23.906939 -23.906939]
  [-25.452368 -25.452368 -25.452368]
  ...
  [-39.97793  -39.97793  -39.97793 ]
  [-31.852644 -31.852644 -31.852644]
  [-26.244059 -26.244059 -26.244059]]

 [[-26.092194 -26.092194 -26.092194]
  [-24.175066 -24.175066 -24.175066]
  [-13.649515 -13.649515 -13.649515]
  ...
  [-33.09472  -33.09472  -33.09472 ]
  [-24.535719 -24.535719 -24.535719]
  [-21.979366 -21.979366 -21.979366]]

 [[-47.068626 -47.068626 -47.068626]
  [-29.675768 -29.675768 -29.675768]
  [-23.72275  -23.72275  -23.72275 ]
  ...
  [-31.098347 -31.098347 -31.098347]
  [-32.971466 -32.971466 -32.971466]
  [-29.667307 -29.667307 -29.667307]]

 ...

 [[-80.       -80.       -80.      ]
  [-80.       -80.       -80.      ]
  [-80.       -80.       -80.      ]
  ...
  [-80.       -80.       -80.      ]
  [-80.       -80.       -80.      ]
  [-80.       -80.       -80.      ]]

 [[-80.       -80.       -80.      ]
  [-80.       -80.       -80.      ]


In [77]:
np.save("/content/drive/MyDrive/FYP Data/Train and Test/test_data.npy", test_list)

In [78]:
test = np.load("/content/drive/MyDrive/FYP Data/Train and Test/test_data.npy", allow_pickle = True)
print(test.shape)

(304, 345, 345, 3)


### Obtain train and test labels

In [79]:
df_train

Filename                                Log Mel Spectrogram
270  ambience (110).wav  [[[-33.08299, -33.08299, -33.08299], [-38.4111...
102  ambience (206).wav  [[[-35.107437, -35.107437, -35.107437], [-40.7...
197  ambience (130).wav  [[[-23.944202, -23.944202, -23.944202], [-24.7...
142  ambience (182).wav  [[[-39.812046, -39.812046, -39.812046], [-44.6...
53   ambience (271).wav  [[[-28.620619, -28.620619, -28.620619], [-28.3...
..                  ...                                                ...
112     shout (200).wav  [[[-80.0, -80.0, -80.0], [-80.0, -80.0, -80.0]...
208     shout (150).wav  [[[-66.7005, -66.7005, -66.7005], [-68.86181, ...
164     shout (133).wav  [[[-70.92355, -70.92355, -70.92355], [-65.4657...
40       shout (53).wav  [[[-58.36692, -58.36692, -58.36692], [-58.7806...
84      shout (105).wav  [[[-74.00872, -74.00872, -74.00872], [-73.0564...

[1204 rows x 2 columns]

In [90]:
# Creating an empty list
train_label = []

In [91]:
for item in df_train['Filename']:
  filename = str(item)
  sound_class = filename.split()[0] # Only obtain first word
  if sound_class == "ambience":
    train_label.append(0)
  if sound_class == "footsteps":
    train_label.append(1)
  if sound_class == "horn":
    train_label.append(2)
  if sound_class == "music":
    train_label.append(3)
  if sound_class == "shout":
    train_label.append(4)

train_label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [93]:
df_test

Filename                                Log Mel Spectrogram
167  ambience (132).wav  [[[-44.501633, -44.501633, -44.501633], [-31.9...
318  ambience (321).wav  [[[-20.341702, -20.341702, -20.341702], [-23.5...
72   ambience (252).wav  [[[-24.07206, -24.07206, -24.07206], [-23.9069...
3    ambience (300).wav  [[[-40.819183, -40.819183, -40.819183], [-45.8...
185  ambience (192).wav  [[[-40.354637, -40.354637, -40.354637], [-45.9...
..                  ...                                                ...
202     shout (161).wav  [[[-53.830147, -53.830147, -53.830147], [-57.7...
256     shout (266).wav  [[[-80.0, -80.0, -80.0], [-76.28508, -76.28508...
59       shout (74).wav  [[[-80.0, -80.0, -80.0], [-71.82796, -71.82796...
75      shout (112).wav  [[[-80.0, -80.0, -80.0], [-77.284454, -77.2844...
152     shout (243).wav  [[[-80.0, -80.0, -80.0], [-64.71125, -64.71125...

[304 rows x 2 columns]

In [94]:
# Creating an empty list
test_label = []

In [95]:
for item in df_test['Filename']:
  filename = str(item)
  sound_class = filename.split()[0] # Only obtain first word
  if sound_class == "ambience":
    test_label.append(0)
  if sound_class == "footsteps":
    test_label.append(1)
  if sound_class == "horn":
    test_label.append(2)
  if sound_class == "music":
    test_label.append(3)
  if sound_class == "shout":
    test_label.append(4)

test_label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,


In [98]:
train_label_newdim = np.expand_dims(train_label, axis=1)
test_label_newdim = np.expand_dims(test_label, axis=1)

print(train_label_newdim)

[[0]
 [0]
 [0]
 ...
 [4]
 [4]
 [4]]


In [99]:
np.save("/content/drive/MyDrive/FYP Data/Train and Test/train_label.npy", train_label_newdim)
np.save("/content/drive/MyDrive/FYP Data/Train and Test/test_label.npy", test_label_newdim)

In [100]:
train_labels = np.load("/content/drive/MyDrive/FYP Data/Train and Test/train_label.npy", allow_pickle = True)
test_labels = np.load("/content/drive/MyDrive/FYP Data/Train and Test/test_label.npy", allow_pickle = True)

print(train_labels.shape)
print(test_labels.shape)

(1204, 1)
(304, 1)
